name: gobgc23
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.9   # Python version 3.9 or newer
    - basemap       # mapping package
    - cartopy       # Geographic plotting toolkit
    - dask          # Parallel processing library
    - h5py          # Wrapper for HDF5
    - jupyter       # Jupyter architecture
    - jupyterlab    # Jupyter Lab environment
    - nb_conda_kernels #
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - pandas        # Labeled array library
    - seaborn       # Statistical visualizations
    - xarray        # N-d labeled array library
    - gsw           # TEOS Gibbs Seawater properties
    #- argopy>0.1.13       # argo data - doesn't support bgc reliably yet
    - pip
    - pip:
      - argopy==0.1.14rc2
